# QLoRA Fine-tuning: Llama 3.1/3.2 (1B–3B) on Medical Reasoning

**Dataset:** `OpenMed/Medical-Reasoning-SFT-Mega`  
**Technique:** QLoRA (4-bit quantization + LoRA adapters)  
**Platform:** Google Colab — T4 Free Tier  
**Libraries:** `transformers`, `peft`, `trl`, `bitsandbytes`, `datasets`, `wandb`/`mlflow`, `ollama`/`vllm`

---

## Notebook Flow
1. Install dependencies
2. Configure model & training hyperparameters
3. Load model in 4-bit (QLoRA)
4. Load & preview dataset
5. Before-training inference (baseline)
6. Fine-tune with SFTTrainer
7. After-training inference (comparison)
8. Save & push adapter to HuggingFace Hub
9. (Optional) Run with Ollama or vLLM

## 0. Check GPU & Runtime

In [1]:
import subprocess

# Check GPU
print("=== GPU Info ===")
result = subprocess.run(['nvidia-smi'], capture_output=True, text=True)
print(result.stdout if result.returncode == 0 else 'No GPU detected — make sure Runtime > Change runtime type > T4 GPU is selected!')

# Check available disk space
print("\n=== Disk Space ===")
result2 = subprocess.run(['df', '-h', '/'], capture_output=True, text=True)
print(result2.stdout)

# Check RAM
print("\n=== RAM ===")
result3 = subprocess.run(['free', '-h'], capture_output=True, text=True)
print(result3.stdout)

=== GPU Info ===
Thu Mar 19 19:01:36 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+


=== Disk Space ===
Filesystem      Size  Used Avail Use% Mounted on
overlay         113G   77G   36G  69% /


=== RAM ===
               total        used        free      shared  buff/cache   available
Mem:            12Gi       1.5Gi       2.3Gi       6.0Mi       8.9Gi        10Gi
Swap:             0B          0B          0B

## 1. Install Dependencies

> **Restart the runtime after this cell!** (`Runtime → Restart runtime`)

In [ ]:
import subprocess, sys, pathlib, re

# 1. Install bitsandbytes 
print('\nInstalling bitsandbytes 0.45.3...')
!pip install -q 'bitsandbytes==0.45.3' --no-cache-dir

# 2. Core fine-tuning stack 
print('\nInstalling fine-tuning stack...')
!pip install -q \
    'transformers==4.46.3' \
    'peft==0.13.2' \
    'trl==0.12.2' \
    'accelerate==1.1.1' \
    'datasets==3.1.0' \
    sentencepiece \
    protobuf \
    huggingface_hub

# 3. Optional experiment tracking 
!pip install -q wandb mlflow

# 4. Verify 
print('\n── Verification ──')

bnb_dir = pathlib.Path('/usr/local/lib/python3.12/dist-packages/bitsandbytes')
binaries = sorted(bnb_dir.glob('libbitsandbytes_cuda*.so'))

if not binaries:
    # fallback: search wider
    binaries = sorted(pathlib.Path('/usr/local/lib').rglob('libbitsandbytes_cuda*.so'))

print('bnb CUDA binaries found:')
for b in binaries:
    marker =  if 'cuda128' in b.name else '    '
    print(f'{marker} {b.name}')

cuda128_ok = any('cuda128' in b.name for b in binaries)
if cuda128_ok:
    print('\n libbitsandbytes_cuda128.so present — correct for Colab T4 (CUDA 12.8)')
else:
    print('\n cuda128 binary missing!')
    print('   Try: !pip install bitsandbytes --upgrade --no-cache-dir')

# Version check (subprocess to avoid stale import cache)
r = subprocess.run(
    [sys.executable, '-c', 'import bitsandbytes as bnb; print("bnb", bnb.__version__)'],
    capture_output=True, text=True
)
print(r.stdout.strip() or r.stderr.strip())

print()
print('NOTE: Any "Could not find cuda128.so" WARNING in the subprocess above')
print('      is a stale-cache artifact from the current session — safe to ignore.')
print('      After RESTART the correct .so loads cleanly.')

print('\n' + '='*58)
print('   Installation complete.')
print('   RESTART THE RUNTIME NOW — this is required.')
print('  Runtime → Restart runtime  (or press Ctrl+M then .)')
print('  After restart: run Section 0 → 2 → 2b → 4 onward.')
print('  Do NOT re-run this Section 1 cell after restart.')
print('='*58)

Removing old bitsandbytes (if any)...
Found existing installation: bitsandbytes 0.45.3
Uninstalling bitsandbytes-0.45.3:
  Successfully uninstalled bitsandbytes-0.45.3
Done.

Installing bitsandbytes 0.45.3...
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 152.0 MB/s eta 0:00:00

Installing fine-tuning stack...

── Verification ──
bnb CUDA binaries found:
     libbitsandbytes_cuda117.so
     libbitsandbytes_cuda118.so
     libbitsandbytes_cuda120.so
     libbitsandbytes_cuda121.so
     libbitsandbytes_cuda122.so
     libbitsandbytes_cuda123.so
     libbitsandbytes_cuda124.so
     libbitsandbytes_cuda125.so
     libbitsandbytes_cuda126.so
  ✅ libbitsandbytes_cuda128.so

✅ libbitsandbytes_cuda128.so present — correct for Colab T4 (CUDA 12.8)
bnb 0.45.3

NOTE: Any "Could not find cuda128.so" WARNING in the subprocess above
      is a stale-cache artifact from the current session — safe to ignore.
      After RESTART the correct .so loads cleanly.

==========================================================
  ✅  Installation complete.
  ⚠️  RESTART THE RUNTIME NOW — this is required.
  Runtime → Restart runtime  (or press Ctrl+M then .)
  After restart: run Section 0 → 2 → 2b → 4 onward.
  Do NOT re-run this Section 1 cell after restart.
==========================================================

## 2. Configuration — Edit This Cell First!

In [ ]:
import os

# Llama 3.2 1B 
MODEL_ID = "meta-llama/Llama-3.2-1B-Instruct"

# Llama 3.2 3B 
# MODEL_ID = "meta-llama/Llama-3.2-3B-Instruct"

# Llama 3.1 8B 
# MODEL_ID = "meta-llama/Meta-Llama-3.1-8B-Instruct"

#  DATASET
DATASET_ID     = "OpenMed/Medical-Reasoning-SFT-Mega"
SUBSET_SIZE    = 100    # Small subset for quick testing
USE_FULL_DATA  = False   # Set True to train on full dataset


#  OUTPUT
OUTPUT_DIR     = "./llama-medical-qlora"
HF_USERNAME    = "aakashaldankar"   # For pushing to Hub (optional)
ADAPTER_NAME   = "llama-medical-qlora-adapter"


#  QLoRA HYPERPARAMETERS
LORA_R         = 16      # LoRA rank — higher = more params, more expressiveness
LORA_ALPHA     = 32      # LoRA scaling factor (typically 2x rank)
LORA_DROPOUT   = 0.05
TARGET_MODULES = ["q_proj", "k_proj", "v_proj", "o_proj",
                  "gate_proj", "up_proj", "down_proj"]  # All linear layers


#  TRAINING HYPERPARAMETERS
NUM_EPOCHS           = 2        
PER_DEVICE_BATCH     = 2        
GRAD_ACCUM_STEPS     = 8        
LEARNING_RATE        = 2e-4
MAX_SEQ_LENGTH       = 1024     
WARMUP_RATIO         = 0.05
LR_SCHEDULER         = "cosine"
LOGGING_STEPS        = 10
SAVE_STEPS           = 100


#  EXPERIMENT TRACKING (set one)
USE_WANDB   = True   # Set True + add your WANDB_API_KEY
USE_MLFLOW  = False   # Set True for local mlflow tracking


#  HUGGINGFACE AUTH 
HF_TOKEN = os.environ.get("HF_TOKEN", "")

print(" Configuration loaded.")
print(f" Model      : {MODEL_ID}")
print(f" Dataset    : {DATASET_ID}")
print(f" Subset size: {SUBSET_SIZE if not USE_FULL_DATA else 'FULL'}")
print(f" LoRA rank  : {LORA_R}")
print(f" Epochs     : {NUM_EPOCHS}")

✅ Configuration loaded.
   Model      : meta-llama/Llama-3.2-1B-Instruct
   Dataset    : OpenMed/Medical-Reasoning-SFT-Mega
   Subset size: 100
   LoRA rank  : 16
   Epochs     : 2

## 2b. Authenticate HuggingFace

Llama models are **gated**. You must:
1. Create a free HuggingFace account
2. Accept the Llama license at https://huggingface.co/meta-llama/Llama-3.2-3B-Instruct
3. Create a read token at https://huggingface.co/settings/tokens
4. Add it as a Colab Secret named HF_TOKEN (key icon in the left panel)

In [ ]:
from huggingface_hub import login
from google.colab import userdata

try:
    # Try Colab Secrets first (recommended)
    hf_token = userdata.get('HF_TOKEN')
    login(token=hf_token, add_to_git_credential=False)
    print(" Logged in via Colab Secrets.")
except Exception:
    if HF_TOKEN:
        login(token=HF_TOKEN, add_to_git_credential=False)
        print(" Logged in via config variable.")
    else:
        print(" No HF_TOKEN found. Using interactive login...")
        login()   # Will prompt for token

✅ Logged in via Colab Secrets.

## 3. Load Dataset

In [4]:
from datasets import load_dataset
import pandas as pd

print(f"Loading dataset: {DATASET_ID}")

# Load dataset (streaming=True avoids downloading all data upfront)
raw_dataset = load_dataset(DATASET_ID, split="train")

print(f"\nFull dataset size: {len(raw_dataset):,} samples")
print(f"Columns: {raw_dataset.column_names}")
print(f"\nSample entry:")
print(raw_dataset[0])

Loading dataset: OpenMed/Medical-Reasoning-SFT-Mega

Resolving data files:   0%|          | 0/34 [00:00<?, ?it/s]

Loading dataset shards:   0%|          | 0/29 [00:00<?, ?it/s]

Full dataset size: 1,789,998 samples
Columns: ['messages']

Sample entry:
{'messages': [{'content': 'Which of the following is **not** a common method by which bacteria can acquire new genetic material?\nA: Conjugation\nB: Transduction\nC: Transformation\nD: Binary fission\nE: Plasmid uptake\nF: Integron shuffling\nG: Transposition\nH: Phage-mediated gene transfer\nI: Gene cassettes integration\nJ: Horizontal gene transfer via conjugative elements', 'reasoning_content': None, 'role': 'user'}, {'content': 'The question asks which option is not a common method for bacteria to acquire new genetic material. Bacteria acquire new genetic material primarily through horizontal gene transfer mechanisms, which involve the uptake or transfer of DNA from external sources. The options include:\n\n- **A: Conjugation**: A process where bacteria transfer genetic material directly through cell-to-cell contact, such as via a pilus. This is a common method.\n- **B: Transduction**: A process where bacteriophages (viruses) transfer DNA between bacteria. This is a common method.\n- **C: Transformation**: A process where bacteria take up free DNA from the environment and incorporate it into their genome. This is a common method.\n- **D: Binary fission**: A form of asexual reproduction where a single bacterial cell divides into two identical daughter cells. This does not involve acquiring new genetic material; it is a method of cell division and replication of existing DNA.\n- **E: Plasmid uptake**: The process by which bacteria incorporate plasmids (small, circular DNA molecules) from the environment or other cells. This is a common method, often associated with transformation.\n- **F: Integron shuffling**: A process where integrons capture and express gene cassettes, facilitating the acquisition of new genes. This is a common method.\n- **G: Transposition**: The movement of transposons (jumping genes) within the genome, which can facilitate gene transfer, especially in horizontal gene transfer contexts. This is a common mechanism.\n- **H: Phage-mediated gene transfer**: A synonym for transduction, where bacteriophages transfer DNA between bacteria. This is a common method.\n- **I: Gene cassettes integration**: The process by which gene cassettes are integrated into integrons, allowing for the acquisition of new genetic elements. This is a common method.\n- **J: Horizontal gene transfer via conjugative elements**: A process where conjugative plasmids or elements enable the transfer of DNA between bacteria. This is a common method.\n\nBinary fission (option D) is not a method for acquiring new genetic material; it is a reproductive process that involves the replication and division of existing genetic material without introducing new DNA from external sources. Therefore, it is the correct choice for the option that is not a common method.\n\n**Answer: D**\n\nD', 'reasoning_content': 'First, the question is: "Which of the following is not a common method by which bacteria can acquire new genetic material?" I need to find the option that doesn\'t fit as a method for bacteria to get new genetic material.\n\nThe options are:\n\nA: Conjugation\n\nB: Transduction\n\nC: Transformation\n\nD: Binary fission\n\nE: Plasmid uptake\n\nF: Integron shuffling\n\nG: Transposition\n\nH: Phage-mediated gene transfer\n\nI: Gene cassettes integration\n\nJ: Horizontal gene transfer via conjugative elements\n\nI should recall what each of these terms means in the context of bacterial genetics.\n\nStarting with A: Conjugation. This is when bacteria transfer genetic material through direct contact, like via a pilus. It\'s a common way for bacteria to share plasmids or other DNA.\n\nB: Transduction. This involves bacteriophages (viruses) transferring DNA from one bacterium to another. It\'s another standard method.\n\nC: Transformation. This is when bacteria take up free DNA from the environment and incorporate it into their genome. Very common.\n\nD: Binary fission. This is how bacteria reproduce asexually. One cell divides into two identical cells. It\'s not a method for acquiring new genetic material; it\'s just reproduction. In binary fission, the genetic material is copied and passed on, but it\'s not acquiring new material from outside. It\'s vertical gene transfer, not horizontal.\n\nE: Plasmid uptake. This sounds similar to transformation, where bacteria take up plasmids. Plasmids are often transferred via conjugation or transformation, so this could be a method.\n\nF: Integron shuffling. Integrons are genetic elements that can capture and express gene cassettes. They\'re involved in horizontal gene transfer, especially for antibiotic resistance genes. So, this is a method.\n\nG: Transposition. Transposons are "jumping genes" that can move within the genome. They can be involved in acquiring new genetic material by inserting into different locations, but transposition itself is a mechanism that can facilitate gene transfer, often in conjunction with other methods.\n\nH: Phage-mediated gene transfer. This is essentially transduction, which is already listed as B. Transduction is a form of phage-mediated gene transfer.\n\nI: Gene cassettes integration. This is related to integrons, where gene cassettes are integrated into the integron. It\'s a way to acquire new genes.\n\nJ: Horizontal gene transfer via conjugative elements. Conjugative elements are parts of the plasmid or chromosome that enable conjugation. So, this is another way to describe conjugation.\n\nNow, looking back at D: Binary fission. Binary fission is the process of cell division. It doesn\'t involve acquiring new genetic material; it\'s just replicating existing DNA. Bacteria can acquire new genetic material through other means, but binary fission itself is not one of them.\n\nLet me double-check the other options to make sure.\n\n- Conjugation: Yes, horizontal gene transfer.\n\n- Transduction: Yes, via phages.\n\n- Transformation: Yes, uptake of free DNA.\n\n- Plasmid uptake: This is often part of transformation or conjugation.\n\n- Integron shuffling: Integrons facilitate the capture of gene cassettes.\n\n- Transposition: Transposons can move genes around, but they don\'t typically acquire new material from outside; they move existing material. However, transposition can be involved in horizontal gene transfer when transposons carry genes from one organism to another.\n\n- Phage-mediated gene transfer: Same as transduction.\n\n- Gene cassettes integration: Part of integron function.\n\n- Horizontal gene transfer via conjugative elements: Conjugation.\n\nSo, binary fission stands out because it\'s not a method for acquiring new genetic material; it\'s a reproductive process.\n\nThe question says "acquire new genetic material," which implies gaining DNA from outside the cell, not just replicating what\'s already there.\n\nIn binary fission, the cell divides, and each daughter cell gets a copy of the DNA, but no new DNA is added from an external source. So, it doesn\'t fit.\n\nAll the other options involve some form of horizontal gene transfer or mechanisms that allow DNA to be acquired from the environment or other cells.\n\nFor example, transposition can be involved in horizontal gene transfer when transposons jump into plasmids or chromosomes from external sources, but the primary mechanism for acquisition is still conjugation, transduction, or transformation.\n\nBut binary fission is clearly not a method for acquisition.\n\nAlso, option H is "Phage-mediated gene transfer," which is transduction, and B is transduction, so they might be redundant, but both are valid methods.\n\nSimilarly, J is "Horizontal gene transfer via conjugative elements," which is conjugation.\n\nBut the question is to find which is not common, and binary fission is not a method at all for acquisition.\n\nI think D is the correct choice.\n\nLet me see if there\'s any trick. Is there any context where binary fission could be considered? Like, in some cases, binary fission might be confused with other processes, but no, it\'s straightforward.\n\nPerhaps in some bacteria, but no, binary fission is universal for bacterial reproduction and doesn\'t involve genetic exchange.\n\nSo, I believe D: Binary fission is the answer.', 'role': 'assistant'}]}

In [5]:
from datasets import Dataset

# ── Subset selection ──────────────────────────────────────────────
if USE_FULL_DATA:
    dataset = raw_dataset
    print(f"Using FULL dataset: {len(dataset):,} samples")
else:
    dataset = raw_dataset.select(range(min(SUBSET_SIZE, len(raw_dataset))))
    print(f"Using SUBSET: {len(dataset):,} samples (set USE_FULL_DATA=True for full training)")

# ── Inspect schema ────────────────────────────────────────────────
# The OpenMed dataset typically has 'instruction', 'output' or 'messages' fields.
# Adapt the formatter below to match actual column names.
sample = dataset[0]
print("\nDataset columns:", list(sample.keys()))

# Train / eval split (90/10)
split = dataset.train_test_split(test_size=0.1, seed=42)
train_data = split["train"]
eval_data  = split["test"]

print(f"\nTrain: {len(train_data):,} | Eval: {len(eval_data):,}")

Using SUBSET: 100 samples (set USE_FULL_DATA=True for full training)

Dataset columns: ['messages']

Train: 90 | Eval: 10

In [ ]:
# Inspect real column names 
sample = dataset[0]
print('Dataset columns:', list(sample.keys()))
print('\nFirst example (truncated):')
for k, v in sample.items():
    print(f'  {k}: {str(v)[:200]}')

# System prompt 
SYSTEM_PROMPT = (
    'You are a highly knowledgeable medical assistant. '
    'Answer the following clinical question accurately, step-by-step, '
    'citing reasoning and evidence where applicable.'
)

# Define formatter
def format_to_text(example, tok):
    """
    Converts a dataset row to a single rendered string using the
    tokenizer's chat template.  Works with both:
      • 'messages' schema  (list-of-dicts)
      • flat 'instruction'/'output' schema
    """
    cols = set(example.keys())

    if 'messages' in cols:
        messages = list(example['messages'])
        # Ensure system message is present
        if not messages or messages[0].get('role') != 'system':
            messages = [{'role': 'system', 'content': SYSTEM_PROMPT}] + messages
    else:
        instruction = (
            example.get('instruction') or example.get('input')
            or example.get('question')  or example.get('prompt') or ''
        )
        output = (
            example.get('output')    or example.get('response')
            or example.get('answer') or example.get('completion') or ''
        )
        messages = [
            {'role': 'system',    'content': SYSTEM_PROMPT},
            {'role': 'user',      'content': str(instruction).strip()},
            {'role': 'assistant', 'content': str(output).strip()},
        ]

    # add_generation_prompt=False → includes the assistant turn (training mode)
    text = tok.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False,
    )
    return {'text': text}

print('\n Formatter defined. Dataset will be formatted in Section 3b')
print('   (after the tokenizer is loaded in Section 4).')

Dataset columns: ['messages']

First example (truncated):
  messages: [{'content': 'Which of the following is **not** a common method by which bacteria can acquire new genetic material?\nA: Conjugation\nB: Transduction\nC: Transformation\nD: Binary fission\nE: Plasmid u

✅ Formatter defined. Dataset will be formatted in Section 3b
   (after the tokenizer is loaded in Section 4).

## 4. Load Base Model (4-bit QLoRA)

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
import pathlib

# Sanity check 1: CUDA 
assert torch.cuda.is_available(), (
    "CUDA not available! Go to Runtime → Change runtime type → T4 GPU, then restart."
)
print(f" CUDA {torch.version.cuda} | GPU: {torch.cuda.get_device_name(0)}")

# Sanity check 2: bitsandbytes CUDA binary
import bitsandbytes as bnb
bnb_dir = pathlib.Path(bnb.__file__).parent
cuda_so_files = sorted(bnb_dir.glob("libbitsandbytes_cuda*.so"))
if not cuda_so_files:
    raise RuntimeError(
        "No bitsandbytes CUDA binary found!\n"
        "Re-run Section 1 (install cell), then Runtime → Restart runtime."
    )
# Pick the .so that best matches the current CUDA version
cuda_ver = torch.version.cuda.replace(".", "")          # e.g. "128"
best_so  = next((s for s in cuda_so_files if cuda_ver in s.name), cuda_so_files[-1])
print(f"bitsandbytes {bnb.__version__} | using {best_so.name}")

# 4-bit quantization config (QLoRA)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

# Tokenizer
print(f"\nLoading tokenizer: {MODEL_ID}")
tokenizer = AutoTokenizer.from_pretrained(
    MODEL_ID,
    trust_remote_code=True,
    padding_side="right",
)
if tokenizer.pad_token is None:
    tokenizer.pad_token     = tokenizer.eos_token
    tokenizer.pad_token_id  = tokenizer.eos_token_id

print(f"Vocab size    : {tokenizer.vocab_size:,}")
print(f"Pad token     : {tokenizer.pad_token}")
print(f"Chat template : {'Yes' if tokenizer.chat_template else 'No'}")

# Base model
print(f"\nLoading model: {MODEL_ID} in 4-bit...")
base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True,
    attn_implementation="eager",
)
base_model.config.use_cache      = False
base_model.config.pretraining_tp = 1

total_params     = sum(p.numel() for p in base_model.parameters())
trainable_params = sum(p.numel() for p in base_model.parameters() if p.requires_grad)
print(f"\n Model loaded.")
print(f"   Total params    : {total_params/1e9:.2f}B")
print(f"   Trainable params: {trainable_params/1e6:.2f}M (before LoRA)")

✅ CUDA 12.8 | GPU: Tesla T4
✅ bitsandbytes 0.45.3 | using libbitsandbytes_cuda128.so

Loading tokenizer: meta-llama/Llama-3.2-1B-Instruct
Vocab size    : 128,000
Pad token     : <|eot_id|>
Chat template : Yes

Loading model: meta-llama/Llama-3.2-1B-Instruct in 4-bit...

✅ Model loaded.
   Total params    : 0.75B
   Trainable params: 262.74M (before LoRA)

In [ ]:
# Section 3b — Apply chat template

print('Applying chat template to train / eval sets...')

train_data = train_data.map(
    lambda ex: format_to_text(ex, tokenizer),
    remove_columns=train_data.column_names,
    desc='Formatting train set',
)
eval_data = eval_data.map(
    lambda ex: format_to_text(ex, tokenizer),
    remove_columns=eval_data.column_names,
    desc='Formatting eval set',
)

print('\n Dataset formatted — column is now "text" (plain string).')
print(f'   Train: {len(train_data):,}  |  Eval: {len(eval_data):,}')
print('\nFormatted sample (first 600 chars):')
print(train_data[0]['text'][:600])

Applying chat template to train / eval sets...

Formatting train set:   0%|          | 0/90 [00:00<?, ? examples/s]

Formatting eval set:   0%|          | 0/10 [00:00<?, ? examples/s]

✅ Dataset formatted — column is now "text" (plain string).
   Train: 90  |  Eval: 10

Formatted sample (first 600 chars):
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 19 Mar 2026

You are a knowledgeable and compassionate medical assistant. Your role is to provide accurate, evidence-based medical information while being clear and helpful.

Guidelines:
- Provide thorough, well-reasoned answers based on current medical knowledge
- Explain medical concepts in clear, accessible language
- When appropriate, mention when someone should seek professional medical care
- Be empathetic and supportive in your responses
- If a question is outside your expertis

## 5. EFORE Training — Baseline Inference

We run the **untrained model** on a fixed set of medical questions. We'll compare these answers to the fine-tuned model later.

In [ ]:
# Benchmark questions: these will be tested before AND after training
BENCHMARK_QUESTIONS = [
    "What is the first-line treatment for Type 2 Diabetes Mellitus in a newly diagnosed patient?",
    "A 65-year-old male presents with sudden onset chest pain radiating to the left arm, diaphoresis, and nausea. What is the most likely diagnosis and immediate management?",
    "Explain the mechanism of action of beta-lactam antibiotics and describe two mechanisms of bacterial resistance.",
    "What are the diagnostic criteria for Systemic Lupus Erythematosus (SLE) according to the 2019 EULAR/ACR classification?",
    "A child presents with high fever, stiff neck, photophobia, and a petechial rash. What is the differential diagnosis and emergency treatment?",
]


def run_inference(model, tokenizer_obj, question, max_new_tokens=400, label="Model"):
    """Run a single inference pass and return the generated answer."""
    messages = [
        {"role": "system",  "content": SYSTEM_PROMPT},
        {"role": "user",    "content": question},
    ]
    # Format using the model's chat template
    prompt = tokenizer_obj.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )
    inputs = tokenizer_obj(prompt, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            temperature=0.3,
            do_sample=True,
            top_p=0.9,
            repetition_penalty=1.1,
            pad_token_id=tokenizer_obj.pad_token_id,
            eos_token_id=tokenizer_obj.eos_token_id,
        )

    # Decode only newly generated tokens
    new_tokens = outputs[0][inputs["input_ids"].shape[-1]:]
    answer = tokenizer_obj.decode(new_tokens, skip_special_tokens=True)
    return answer.strip()


def pretty_print_comparison(question, before, after=None):
    """Pretty-print a before/after comparison."""
    sep = "─" * 70
    print(f"\n{'═'*70}")
    print(f"QUESTION: {question}")
    print(sep)
    print(f"BEFORE FINE-TUNING:\n{before}")
    if after is not None:
        print(sep)
        print(f"AFTER FINE-TUNING:\n{after}")
    print(f"{'═'*70}\n")

print("✅ Inference helpers ready.")

✅ Inference helpers ready.

In [ ]:
# Run baseline inference
print(" Running BASELINE inference (before fine-tuning)...\n")

before_answers = {}
for i, q in enumerate(BENCHMARK_QUESTIONS, 1):
    print(f"[{i}/{len(BENCHMARK_QUESTIONS)}] Generating answer...")
    answer = run_inference(base_model, tokenizer, q)
    before_answers[q] = answer
    pretty_print_comparison(q, answer)

print("\n Baseline inference complete. Answers stored in `before_answers`.")

🔴 Running BASELINE inference (before fine-tuning)...

[1/5] Generating answer...

══════════════════════════════════════════════════════════════════════
❓ QUESTION: What is the first-line treatment for Type 2 Diabetes Mellitus in a newly diagnosed patient?
──────────────────────────────────────────────────────────────────────
🔴 BEFORE FINE-TUNING:
For a newly diagnosed patient with Type 2 Diabetes Mellitus (T2DM), the first-line treatment typically involves lifestyle modifications and/or oral medications. Here's a step-by-step approach:

**Lifestyle Modifications:**

1. **Weight Loss**: Aiming to lose 5-10% of body weight within 12 weeks can help improve insulin sensitivity and reduce HbA1c levels.
2. **Dietary Changes**: Focus on whole, unprocessed foods, including:
	* Vegetables (aim for 5 servings/day)
	* Fruits (aim for 4 servings/day)
	* Whole grains (aim for 6 servings/day)
	* Lean protein sources (aim for 2 servings/day)
	* Healthy fats (limit saturated fat intake)
3. **Physical Activity**: Aim for at least 150 minutes of moderate-intensity aerobic exercise or 75 minutes of vigorous-intensity aerobic exercise per week.

**Oral Medications:**

1. **Metformin**: This is often considered the first-line medication for T2DM due to its efficacy in improving glycemic control and reducing cardiovascular risk.
2. **Sulfonylureas**: These medications stimulate insulin release from the pancreas, but they may have side effects such as hypoglycemia (low blood sugar) and increased gastrointestinal side effects.
3. **Thiazolidinediones**: These medications also increase insulin secretion, but they may be more effective than sulfonylureas for some patients.
4. **GLP-1 receptor agonists**: These medications mimic the action of incretin hormones to decrease postprandial glucose excursions and improve glycemic control.

**Additional Considerations:**

1. **Insulin Therapy**: For patients who do not respond to initial pharmacological therapy, insulin therapy may be necessary to maintain tight glycemic control.
2. **Monitoring**: Regular monitoring of blood glucose, HbA1c, and lipid profiles will continue throughout
══════════════════════════════════════════════════════════════════════

[2/5] Generating answer...

══════════════════════════════════════════════════════════════════════
❓ QUESTION: A 65-year-old male presents with sudden onset chest pain radiating to the left arm, diaphoresis, and nausea. What is the most likely diagnosis and immediate management?
──────────────────────────────────────────────────────────────────────
🔴 BEFORE FINE-TUNING:
Given the patient's presentation of sudden onset chest pain radiating to the left arm, diaphoresis (sweating), and nausea in a 65-year-old male, I would diagnose the condition as angina pectoris or possibly myocardial infarction (MI). The symptoms suggest acute coronary syndrome (ACS) given the sudden onset of chest pain.

**Diagnosis:**

Angina pectoris is characterized by chest pain that occurs when the heart muscle does not receive enough oxygen-rich blood flow due to reduced cardiac output. This can be caused by coronary artery disease, which narrows or blocks the coronary arteries supplying the heart.

The symptoms you've described fit well with ACS, particularly angina pectoris, which is often associated with:

1. Sudden onset of chest pain or discomfort radiating to the left arm (the "anginal zone")
2. Shortness of breath or difficulty breathing
3. Nausea or vomiting
4. Diaphoresis (sweating)

**Immediate Management:**

Given the potential for ACS, it is essential to manage the situation promptly. Here's an outline of the steps to take:

1. **Call emergency services:** If possible, call 911 or your local emergency number immediately.
2. **Assess the patient's vital signs:** Check the patient's pulse, blood pressure, respiratory rate, and oxygen saturation.
3. **Administer oxygen:** Provide supplemental oxygen if available, but do not use high concentrations unless instructed otherwise by a healthcare professional.
4. **Apply the Heimlich maneuver (if necessary):** If the patient is unresponsive or shows signs of impending airway obstruction, perform the Heimlich maneuver to dislodge the object from the airway.
5. **Chest compressions and defibrillation (if indicated):** If the patient is in cardiac arrest, perform cardiopulmonary resuscitation (CPR) according to American Heart Association guidelines.
6.
══════════════════════════════════════════════════════════════════════

[3/5] Generating answer...

══════════════════════════════════════════════════════════════════════
❓ QUESTION: Explain the mechanism of action of beta-lactam antibiotics and describe two mechanisms of bacterial resistance.
──────────────────────────────────────────────────────────────────────
🔴 BEFORE FINE-TUNING:
I'll provide an explanation of the mechanism of action of beta-lactam antibiotics and describe two mechanisms of bacterial resistance.

**Mechanism of Action of Beta-Lactam Antibiotics**

Beta-lactam antibiotics work by inhibiting bacterial cell wall synthesis. They bind to penicillin-binding proteins (PBPs) located in the bacterial cell membrane, which are responsible for binding to the beta-lactam ring of the antibiotic. This binding blocks the enzyme transpeptidase, which is necessary for synthesizing the bacterial cell wall.

The beta-lactam ring is composed of six carbon atoms, with a beta-lactam structure that consists of a five-membered ring system. The beta-lactam ring is formed through the condensation reaction between the carboxyl group (-COOH) on one molecule and the amino group (-NH2) on another molecule.

When beta-lactam antibiotics bind to PBPs, they disrupt the normal functioning of the cell wall synthesis pathway. Specifically:

1. **Inhibition of transpeptidase**: By blocking the transpeptidase enzyme, beta-lactam antibiotics prevent the incorporation of new peptidoglycan units into the bacterial cell wall.
2. **Disruption of cross-linking**: The beta-lactam ring also prevents the cross-linking of peptidoglycan molecules, leading to weakened cell walls and ultimately, cell lysis.

This mechanism of action leads to the death of susceptible bacteria, as the bacterial cell wall breaks down and eventually dies due to lack of structural integrity.

**Two Mechanisms of Bacterial Resistance to Beta-Lactam Antibiotics**

1. **Mechanism of Reduced Metabolism (MRSA)**:
Bacteria can develop resistance to beta-lactam antibiotics through reduced metabolism. MRSA bacteria have enzymes that can break down or modify the beta-lactam ring, rendering the antibiotic ineffective. One such enzyme is beta-lactamase, which can hydro
══════════════════════════════════════════════════════════════════════

[4/5] Generating answer...

══════════════════════════════════════════════════════════════════════
❓ QUESTION: What are the diagnostic criteria for Systemic Lupus Erythematosus (SLE) according to the 2019 EULAR/ACR classification?
──────────────────────────────────────────────────────────────────────
🔴 BEFORE FINE-TUNING:
According to the 2019 European League Against Rheumatism (EULAR)/American College of Rheumatology (ACR) classification, the diagnostic criteria for Systemic Lupus Erythematosus (SLE) include:

**Clinical Criteria**

1. **Symptoms**: The patient must have at least two symptoms that meet one or more of the following:
   - Malar rash (butterfly-shaped lesions on the face)
   - Discoid rashes (flat, red patches on the skin)
   - Photosensitivity (sensitivity to sunlight)
   - Oral ulcers (sores in the mouth)
   - Arthritis (joint pain and swelling)
   - Kidney involvement (hematuria, proteinuria, or renal insufficiency)

2. **Laboratory Findings**
   - Positive antinuclear antibody (ANA) test (≥1:40) with no other ANA positivity
   - Anti-dsDNA antibodies (≥1:100)
   - Anti-CCP antibodies (≥1:160)
   - Anti-histone antibodies (≥1:80)
   - Low complement levels (<60% of normal)

**Radiological Criteria**

1. **Bilateral joint inflammation**: Radiographic evidence of joint inflammation (erosions, tendinitis, or synovitis) in at least three joints.
2. **Systemic lupus erythematosus (SLE) nephritis**: Renal involvement, including:
   - Hematuria (>500 mg/day)
   - Proteinuria (>300 mg/day)
   - Renal insufficiency (eGFR <30 mL/min/1.73 m^2)

**Other Criteria**

1. **Autoantibody positivity**: Presence of any of the following autoantibodies:
   - Anti-thyroid peroxidase (anti-TPO)
   - Anti-smooth muscle antibodies (anti-SSA/Ro)
   - Anti-centromere
══════════════════════════════════════════════════════════════════════

[5/5] Generating answer...

══════════════════════════════════════════════════════════════════════
❓ QUESTION: A child presents with high fever, stiff neck, photophobia, and a petechial rash. What is the differential diagnosis and emergency treatment?
──────────────────────────────────────────────────────────────────────
🔴 BEFORE FINE-TUNING:
Given the symptoms of high fever, stiff neck, photophobia (fear of light), and petechial rash in a child, here's a step-by-step approach to determine the differential diagnosis and potential emergency treatment:

**Differential Diagnosis:**

1. **Infectious Diseases**: The presence of fever, stiff neck, and petechial rash suggests an infectious cause.
2. **Neurological Conditions**: The stiff neck and photophobia could indicate meningitis or encephalitis, which require immediate attention.
3. **Bloodborne Pathogens**: Petechial rash can be associated with viral infections such as herpes simplex virus (HSV) or varicella-zoster virus (VZV).
4. **Other Possible Causes**: Other possible causes include allergic reactions, autoimmune disorders, or other systemic illnesses.

**Emergency Treatment:**

Considering the severity of symptoms, I would recommend the following emergency treatment:

1. **Administer Antibiotics**: Administer intravenous antibiotics (e.g., ceftriaxone or vancomycin) to cover a broad spectrum of pathogens, including Streptococcus pneumoniae, Haemophilus influenzae, and Neisseria gonorrhoeae.
2. **Antiviral Therapy**: For HSV or VZV infection, consider antiviral medications like acyclovir or valacyclovir.
3. **Fluid Resuscitation**: Provide aggressive fluid resuscitation to manage dehydration and prevent shock.
4. **Oxygen Support**: Ensure adequate oxygenation by providing supplemental oxygen if necessary.
5. **Monitoring**: Continuously monitor the child for signs of worsening symptoms, such as increased fever, stiff neck, or changes in mental status.
6. **Phototherapy**: Consider phototherapy (UV-A light therapy) to treat HSV or VZV infection, especially if antiviral medication is not effective.
7. **Immunoglobulin**: Administer immunoglobulin (IVIG) to treat Kawasaki disease
══════════════════════════════════════════════════════════════════════


✅ Baseline inference complete. Answers stored in `before_answers`.

## 6. Apply QLoRA (LoRA Adapters) with PEFT

In [ ]:
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, TaskType

# Prepare model for k-bit training (required before adding LoRA)
base_model = prepare_model_for_kbit_training(
    base_model,
    use_gradient_checkpointing=True,  # Saves memory at cost of speed
)

# LoRA configuration
lora_config = LoraConfig(
    r=LORA_R,
    lora_alpha=LORA_ALPHA,
    target_modules=TARGET_MODULES,
    lora_dropout=LORA_DROPOUT,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
    inference_mode=False,
)

model = get_peft_model(base_model, lora_config)

# Print trainable parameters summary
model.print_trainable_parameters()

total     = sum(p.numel() for p in model.parameters())
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
pct       = 100 * trainable / total

print(f"\n QLoRA applied.")
print(f"   Total params    : {total/1e6:.1f}M")
print(f"   Trainable (LoRA): {trainable/1e6:.3f}M ({pct:.2f}%)")
print(f"   Frozen (4-bit)  : {(total - trainable)/1e6:.1f}M")

trainable params: 11,272,192 || all params: 1,247,086,592 || trainable%: 0.9039

✅ QLoRA applied.
   Total params    : 760.5M
   Trainable (LoRA): 11.272M (1.48%)
   Frozen (4-bit)  : 749.3M

## 7. Experiment Tracking (Optional — WandB / MLflow)

In [ ]:
import os

if USE_WANDB:
    import wandb
    from google.colab import userdata

    try:
        wandb_key = userdata.get('WANDB_API_KEY')
    except Exception:
        wandb_key = os.environ.get('WANDB_API_KEY', '')

    if wandb_key:
        wandb.login(key=wandb_key)
    else:
        wandb.login()   # Interactive

    run = wandb.init(
        project="llama-medical-qlora",
        name=f"qlora-r{LORA_R}-{MODEL_ID.split('/')[-1]}",
        config={
            "model": MODEL_ID,
            "dataset": DATASET_ID,
            "subset_size": len(train_data),
            "lora_r": LORA_R,
            "lora_alpha": LORA_ALPHA,
            "epochs": NUM_EPOCHS,
            "lr": LEARNING_RATE,
            "batch_size": PER_DEVICE_BATCH * GRAD_ACCUM_STEPS,
            "max_seq_length": MAX_SEQ_LENGTH,
        },
    )
    print(f" W&B run started: {run.name}")
    os.environ["WANDB_PROJECT"] = "llama-medical-qlora"
    report_to = "wandb"

elif USE_MLFLOW:
    import mlflow
    mlflow.set_experiment("llama-medical-qlora")
    mlflow.start_run(run_name=f"qlora-r{LORA_R}-{MODEL_ID.split('/')[-1]}")
    mlflow.log_params({
        "model": MODEL_ID, "lora_r": LORA_R, "lr": LEARNING_RATE,
        "epochs": NUM_EPOCHS, "subset_size": len(train_data),
    })
    print(" MLflow run started.")
    report_to = "mlflow"   # note: HF doesn't have native mlflow; logs will be manual

else:
    os.environ["WANDB_DISABLED"] = "true"
    report_to = "none"
    print("ℹ Experiment tracking disabled. Set USE_WANDB=True or USE_MLFLOW=True to enable.")

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: [wandb.login()] Using explicit session credentials for https://api.wandb.ai.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: haldankar-aakash-01 (haldankar-aakash-01-proviz) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

✅ W&B run started: qlora-r16-Llama-3.2-1B-Instruct

## 8. Fine-tune with SFTTrainer

In [ ]:
from transformers import TrainingArguments
from trl import SFTTrainer, SFTConfig

# Training arguments optimized for T4 16GB
training_args = SFTConfig(
    # Output 
    output_dir=OUTPUT_DIR,
    run_name=f"qlora-r{LORA_R}",

    # Schedule 
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=PER_DEVICE_BATCH,
    per_device_eval_batch_size=PER_DEVICE_BATCH,
    gradient_accumulation_steps=GRAD_ACCUM_STEPS,

    # Optimizer 
    learning_rate=LEARNING_RATE,
    weight_decay=0.01,
    lr_scheduler_type=LR_SCHEDULER,
    warmup_ratio=WARMUP_RATIO,
    optim="paged_adamw_8bit",   # Memory-efficient optimizer for QLoRA

    # Memory
    max_seq_length=MAX_SEQ_LENGTH,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    fp16=not torch.cuda.is_bf16_supported(),   
    bf16=torch.cuda.is_bf16_supported(),
    dataloader_pin_memory=True,

    # Logging & Saving 
    logging_steps=LOGGING_STEPS,
    save_strategy="steps",
    save_steps=SAVE_STEPS,
    eval_strategy="steps",
    eval_steps=SAVE_STEPS,
    save_total_limit=2,
    load_best_model_at_end=True,
    report_to=report_to,

    # Dataset
    dataset_text_field="text",       
    packing=False,                   

    seed=42,
    group_by_length=True, 
    push_to_hub=False,
)

print(" Training arguments configured.")
print(f"   Effective batch size: {PER_DEVICE_BATCH * GRAD_ACCUM_STEPS}")
print(f"   Precision: {'bf16' if torch.cuda.is_bf16_supported() else 'fp16'}")

✅ Training arguments configured.
   Effective batch size: 16
   Precision: bf16

In [ ]:
# SFTTrainer setup 
trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,   # trl 0.12+ uses processing_class, not tokenizer=
    train_dataset=train_data,
    eval_dataset=eval_data,
    args=training_args,
)

print(' SFTTrainer ready.')
print(f'   Training steps : {len(trainer.get_train_dataloader()) * NUM_EPOCHS}')
print(f'   Eval samples   : {len(eval_data)}')

Map:   0%|          | 0/90 [00:00<?, ? examples/s]

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

✅ SFTTrainer ready.
   Training steps : 90
   Eval samples   : 10

In [ ]:
import time

# TRAIN 
print(" Starting fine-tuning...\n")
start_time = time.time()

train_result = trainer.train()

elapsed = time.time() - start_time
print(f"\n Training complete in {elapsed/60:.1f} minutes.")
print(f"   Final train loss : {train_result.training_loss:.4f}")

# Log metrics
metrics = train_result.metrics
trainer.log_metrics("train", metrics)
trainer.save_metrics("train", metrics)

🚀 Starting fine-tuning...

✅ Training complete in 10.5 minutes.
   Final train loss : 2.0504
***** train metrics *****
  epoch                    =     1.8444
  total_flos               =   782520GF
  train_loss               =     2.0504
  train_runtime            = 0:10:26.20
  train_samples_per_second =      0.287
  train_steps_per_second   =      0.016

In [ ]:
# Save LoRA adapter 
adapter_path = os.path.join(OUTPUT_DIR, "final_adapter")
trainer.model.save_pretrained(adapter_path)
tokenizer.save_pretrained(adapter_path)

print(f" LoRA adapter saved to: {adapter_path}")
!ls -lh {adapter_path}

✅ LoRA adapter saved to: ./llama-medical-qlora/final_adapter
total 60M
-rw-r--r-- 1 root root  735 Mar 19 19:37 adapter_config.json
-rw-r--r-- 1 root root  44M Mar 19 19:37 adapter_model.safetensors
-rw-r--r-- 1 root root 5.0K Mar 19 19:37 README.md
-rw-r--r-- 1 root root  325 Mar 19 19:37 special_tokens_map.json
-rw-r--r-- 1 root root  54K Mar 19 19:37 tokenizer_config.json
-rw-r--r-- 1 root root  17M Mar 19 19:37 tokenizer.json

## 9. AFTER Training — Fine-tuned Inference & Comparison

In [ ]:
from peft import PeftModel

# Enable inference cache
model.config.use_cache = True
model.eval()

print(" Running FINE-TUNED inference (after training)...\n")

after_answers = {}
for i, q in enumerate(BENCHMARK_QUESTIONS, 1):
    print(f"[{i}/{len(BENCHMARK_QUESTIONS)}] Generating answer...")
    answer = run_inference(model, tokenizer, q)
    after_answers[q] = answer

print("\n Fine-tuned inference complete.")

🟢 Running FINE-TUNED inference (after training)...

[1/5] Generating answer...
[2/5] Generating answer...
[3/5] Generating answer...
[4/5] Generating answer...
[5/5] Generating answer...

✅ Fine-tuned inference complete.

In [ ]:
# Side-by-side comparison 
print("\n" + "★" * 70)
print("         BEFORE vs AFTER FINE-TUNING — COMPARISON REPORT")
print("★" * 70)

for q in BENCHMARK_QUESTIONS:
    pretty_print_comparison(
        question=q,
        before=before_answers[q],
        after=after_answers[q],
    )

★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★
         BEFORE vs AFTER FINE-TUNING — COMPARISON REPORT
★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★★

══════════════════════════════════════════════════════════════════════
❓ QUESTION: What is the first-line treatment for Type 2 Diabetes Mellitus in a newly diagnosed patient?
──────────────────────────────────────────────────────────────────────
🔴 BEFORE FINE-TUNING:
For a newly diagnosed patient with Type 2 Diabetes Mellitus (T2DM), the first-line treatment typically involves lifestyle modifications and/or oral medications. Here's a step-by-step approach:

**Lifestyle Modifications:**

1. **Weight Loss**: Aiming to lose 5-10% of body weight within 12 weeks can help improve insulin sensitivity and reduce HbA1c levels.
2. **Dietary Changes**: Focus on whole, unprocessed foods, including:
	* Vegetables (aim for 5 servings/day)
	* Fruits (aim for 4 servings/day)
	* Whole grains (aim for 6 servings/day)
	* Lean protein sources (aim for 2 servings/day)
	* Healthy fats (limit saturated fat intake)
3. **Physical Activity**: Aim for at least 150 minutes of moderate-intensity aerobic exercise or 75 minutes of vigorous-intensity aerobic exercise per week.

**Oral Medications:**

1. **Metformin**: This is often considered the first-line medication for T2DM due to its efficacy in improving glycemic control and reducing cardiovascular risk.
2. **Sulfonylureas**: These medications stimulate insulin release from the pancreas, but they may have side effects such as hypoglycemia (low blood sugar) and increased gastrointestinal side effects.
3. **Thiazolidinediones**: These medications also increase insulin secretion, but they may be more effective than sulfonylureas for some patients.
4. **GLP-1 receptor agonists**: These medications mimic the action of incretin hormones to decrease postprandial glucose excursions and improve glycemic control.

**Additional Considerations:**

1. **Insulin Therapy**: For patients who do not respond to initial pharmacological therapy, insulin therapy may be necessary to maintain tight glycemic control.
2. **Monitoring**: Regular monitoring of blood glucose, HbA1c, and lipid profiles will continue throughout
──────────────────────────────────────────────────────────────────────
🟢 AFTER FINE-TUNING:
For Type 2 diabetes mellitus (T2DM), the first-line treatment typically involves lifestyle modifications and/or oral medications. Here's a step-by-step approach:

**Lifestyle Modifications:**

1. **Weight Loss**: Aim for a body mass index (BMI) of <30 kg/m^2 or <25 kg/m^2 if overweight or obese.
2. **Dietary Changes**:
	* Focus on whole, unprocessed foods like vegetables, fruits, whole grains, lean proteins, and healthy fats.
	* Limit added sugars, saturated fats, and refined carbohydrates.
	* Emphasize omega-3 fatty acids from sources like fatty fish, nuts, and seeds.
3. **Physical Activity**:
	* Aim for at least 150 minutes of moderate-intensity aerobic exercise per week.
	* Incorporate strength training exercises to build muscle mass.
4. **Stress Management**:
	* Practice stress-reducing techniques like yoga, meditation, or deep breathing.

**First-Line Oral Medications:**

1. **Metformin**:
	* A first-line medication for T2DM due to its efficacy, safety profile, and cost-effectiveness.
	* Works by reducing insulin resistance and glucose production in the liver.
2. **Sulfonylureas**:
	* Can be used when metformin is not tolerated or ineffective.
	* Examples include glimepiride, glyburide, and repaglinide.
3. **Thiazolidinediones**:
	* May be used when sulfonylureas are contraindicated or ineffective.
	* Examples include pioglitazone and thalidomide.
4. **GLP-1 Receptor Agonists**:
	* Can be used when sulfonylureas are contraindicated or ineffective.
	* Examples include liraglutide (Victoza) and semaglutide (Oz
══════════════════════════════════════════════════════════════════════


══════════════════════════════════════════════════════════════════════
❓ QUESTION: A 65-year-old male presents with sudden onset chest pain radiating to the left arm, diaphoresis, and nausea. What is the most likely diagnosis and immediate management?
──────────────────────────────────────────────────────────────────────
🔴 BEFORE FINE-TUNING:
Given the patient's presentation of sudden onset chest pain radiating to the left arm, diaphoresis (sweating), and nausea in a 65-year-old male, I would diagnose the condition as angina pectoris or possibly myocardial infarction (MI). The symptoms suggest acute coronary syndrome (ACS) given the sudden onset of chest pain.

**Diagnosis:**

Angina pectoris is characterized by chest pain that occurs when the heart muscle does not receive enough oxygen-rich blood flow due to reduced cardiac output. This can be caused by coronary artery disease, which narrows or blocks the coronary arteries supplying the heart.

The symptoms you've described fit well with ACS, particularly angina pectoris, which is often associated with:

1. Sudden onset of chest pain or discomfort radiating to the left arm (the "anginal zone")
2. Shortness of breath or difficulty breathing
3. Nausea or vomiting
4. Diaphoresis (sweating)

**Immediate Management:**

Given the potential for ACS, it is essential to manage the situation promptly. Here's an outline of the steps to take:

1. **Call emergency services:** If possible, call 911 or your local emergency number immediately.
2. **Assess the patient's vital signs:** Check the patient's pulse, blood pressure, respiratory rate, and oxygen saturation.
3. **Administer oxygen:** Provide supplemental oxygen if available, but do not use high concentrations unless instructed otherwise by a healthcare professional.
4. **Apply the Heimlich maneuver (if necessary):** If the patient is unresponsive or shows signs of impending airway obstruction, perform the Heimlich maneuver to dislodge the object from the airway.
5. **Chest compressions and defibrillation (if indicated):** If the patient is in cardiac arrest, perform cardiopulmonary resuscitation (CPR) according to American Heart Association guidelines.
6.
──────────────────────────────────────────────────────────────────────
🟢 AFTER FINE-TUNING:
**Clinical Question:** A 65-year-old male presents with sudden onset chest pain radiating to the left arm, diaphoresis (sweating), and nausea. The patient's age, symptoms, and potential differential diagnoses suggest a possible acute coronary syndrome (ACS) or cardiac arrhythmia. Given the sudden onset of symptoms, it is essential to promptly assess for cardiac ischemia.

**Step 1: Initial Assessment**

*   **Vital Signs:** Monitor vital signs, including heart rate, blood pressure, respiratory rate, and oxygen saturation.
*   **Physical Examination:** Perform a thorough physical examination, focusing on:
    *   **Chest Pain:** Assess the location, quality, and duration of pain, as well as any radiation to the neck, jaw, or back.
    *   **Systolic Blood Pressure:** Measure systolic blood pressure using a sphygmomanometer or an automated device.
    *   **Respiratory Rate:** Check respiratory rate and assess for signs of distress.
    *   **Oxygen Saturation:** Use pulse oximetry to check oxygen saturation.
*   **Electrocardiogram (ECG):** Obtain an ECG immediately, if feasible, to evaluate for signs of cardiac ischemia or arrhythmias.
*   **Blood Tests:** Order basic laboratory tests, such as:
    *   **Complete Blood Count (CBC):** To rule out infection or other causes of fever.
    *   **Erythrocyte Sedimentation Rate (ESR):** To assess inflammation.
    *   **Lactate Dehydrogenase (LDH):** To evaluate tissue damage.
    *   **Troponin/TnT:** To confirm myocardial infarction (MI).

**Step 2: Differential Diagnosis**

*   **Acute Coronary Syndrome (ACS):**
    *   **Myocardial Infarction (MI):** Evaluate for MI using ECG,
══════════════════════════════════════════════════════════════════════


══════════════════════════════════════════════════════════════════════
❓ QUESTION: Explain the mechanism of action of beta-lactam antibiotics and describe two mechanisms of bacterial resistance.
──────────────────────────────────────────────────────────────────────
🔴 BEFORE FINE-TUNING:
I'll provide an explanation of the mechanism of action of beta-lactam antibiotics and describe two mechanisms of bacterial resistance.

**Mechanism of Action of Beta-Lactam Antibiotics**

Beta-lactam antibiotics work by inhibiting bacterial cell wall synthesis. They bind to penicillin-binding proteins (PBPs) located in the bacterial cell membrane, which are responsible for binding to the beta-lactam ring of the antibiotic. This binding blocks the enzyme transpeptidase, which is necessary for synthesizing the bacterial cell wall.

The beta-lactam ring is composed of six carbon atoms, with a beta-lactam structure that consists of a five-membered ring system. The beta-lactam ring is formed through the condensation reaction between the carboxyl group (-COOH) on one molecule and the amino group (-NH2) on another molecule.

When beta-lactam antibiotics bind to PBPs, they disrupt the normal functioning of the cell wall synthesis pathway. Specifically:

1. **Inhibition of transpeptidase**: By blocking the transpeptidase enzyme, beta-lactam antibiotics prevent the incorporation of new peptidoglycan units into the bacterial cell wall.
2. **Disruption of cross-linking**: The beta-lactam ring also prevents the cross-linking of peptidoglycan molecules, leading to weakened cell walls and ultimately, cell lysis.

This mechanism of action leads to the death of susceptible bacteria, as the bacterial cell wall breaks down and eventually dies due to lack of structural integrity.

**Two Mechanisms of Bacterial Resistance to Beta-Lactam Antibiotics**

1. **Mechanism of Reduced Metabolism (MRSA)**:
Bacteria can develop resistance to beta-lactam antibiotics through reduced metabolism. MRSA bacteria have enzymes that can break down or modify the beta-lactam ring, rendering the antibiotic ineffective. One such enzyme is beta-lactamase, which can hydro
──────────────────────────────────────────────────────────────────────
🟢 AFTER FINE-TUNING:
**Mechanism of Action of Beta-Lactam Antibiotics**

Beta-lactam antibiotics (e.g., penicillins and cephalosporins) work by inhibiting bacterial cell wall synthesis. They bind to penicillin-binding proteins (PBPs), which are enzymes responsible for hydrolyzing the beta-lactam ring of the antibiotic.

Here's how it works:

1. **Binding**: The beta-lactam antibiotic binds to the PBP, causing a conformational change that prevents the enzyme from accessing its active site.
2. **Hydrolysis**: The bound antibiotic disrupts the hydrogen bond between the PBP and the beta-lactam ring, preventing the enzyme from catalyzing the formation of the alpha-1,4-bond between the C5-C6 carbon atoms of the beta-lactam ring.
3. **Inhibition of cell wall synthesis**: Without the ability to form this bond, the bacteria cannot synthesize their cell walls, leading to cell lysis and death.

**Two Mechanisms of Bacterial Resistance to Beta-Lactams**

### **Mechanism 1: Reduced Penetration into the Cell (Permeability)**

Bacteria can develop mechanisms to reduce the penetration of beta-lactam antibiotics into the bacterial cell. These mechanisms include:

*   **Porin-mediated efflux pumps**: Some bacteria produce transporters that pump the antibiotic out of the cell, reducing its intracellular concentration.
*   **Membrane-associated efflux pumps**: Other bacteria use membrane-bound pumps to remove the antibiotic from the cell.
*   **Reduced permeability**: Some bacteria have altered permeability to beta-lactam antibiotics, making them less effective.

### **Mechanism 2: Increased Metabolism or Degradation (Metabolic/Deactivation)**

Bacteria can also develop mechanisms to degrade or inactivate beta-lactam antibiotics through various pathways:

*   **Enzymatic degradation**: Some bacteria produce enzymes
══════════════════════════════════════════════════════════════════════


══════════════════════════════════════════════════════════════════════
❓ QUESTION: What are the diagnostic criteria for Systemic Lupus Erythematosus (SLE) according to the 2019 EULAR/ACR classification?
──────────────────────────────────────────────────────────────────────
🔴 BEFORE FINE-TUNING:
According to the 2019 European League Against Rheumatism (EULAR)/American College of Rheumatology (ACR) classification, the diagnostic criteria for Systemic Lupus Erythematosus (SLE) include:

**Clinical Criteria**

1. **Symptoms**: The patient must have at least two symptoms that meet one or more of the following:
   - Malar rash (butterfly-shaped lesions on the face)
   - Discoid rashes (flat, red patches on the skin)
   - Photosensitivity (sensitivity to sunlight)
   - Oral ulcers (sores in the mouth)
   - Arthritis (joint pain and swelling)
   - Kidney involvement (hematuria, proteinuria, or renal insufficiency)

2. **Laboratory Findings**
   - Positive antinuclear antibody (ANA) test (≥1:40) with no other ANA positivity
   - Anti-dsDNA antibodies (≥1:100)
   - Anti-CCP antibodies (≥1:160)
   - Anti-histone antibodies (≥1:80)
   - Low complement levels (<60% of normal)

**Radiological Criteria**

1. **Bilateral joint inflammation**: Radiographic evidence of joint inflammation (erosions, tendinitis, or synovitis) in at least three joints.
2. **Systemic lupus erythematosus (SLE) nephritis**: Renal involvement, including:
   - Hematuria (>500 mg/day)
   - Proteinuria (>300 mg/day)
   - Renal insufficiency (eGFR <30 mL/min/1.73 m^2)

**Other Criteria**

1. **Autoantibody positivity**: Presence of any of the following autoantibodies:
   - Anti-thyroid peroxidase (anti-TPO)
   - Anti-smooth muscle antibodies (anti-SSA/Ro)
   - Anti-centromere
──────────────────────────────────────────────────────────────────────
🟢 AFTER FINE-TUNING:
The 2019 European League Against Rheumatism (EULAR)/American College of Rheumatology (ACR) classification system is widely used to diagnose SLE. The key diagnostic criteria include:

**Clinical Criteria**

1. **Symptoms**:
    - Arthritis (≥2 joints)
    - Dermatological manifestations (e.g., rash, photosensitivity, oral mucosa lesions)
    - Neurological symptoms (e.g., headache, fatigue, cognitive impairment)
    - Kidney involvement (e.g., proteinuria, hematuria)
    - Other symptoms (e.g., fever, arthralgias, myalgias)

2. **Laboratory Findings**
    - **Antinuclear Antibody (ANA)**:
        - Positive ANA in ≥10% of patients with arthritis or skin disease
        - Positive ANA in ≥20% of patients with nephritis or kidney disease
        - Negative ANA in >90% of patients with normal renal function
    - **Anti-Double-Sandwich Antibodies (cANCA) or Anti-Topoisomerase I (cMPO)**:
        - cANCA positive in ≥5% of patients with arthritis or skin disease
        - cMPO positive in ≥5% of patients with nephritis or kidney disease
    - **Anti-Phospholipase A2 Receptor (PLA2R) Antibody**:
        - Positive in ≥10% of patients with arthritis or skin disease
    - **Anti-Jo-1 Antibody**:
        - Positive in <1% of patients with arthritis or skin disease

**Diagnostic Criteria**

1. **Systemic Disease**:
    - **Nonspecific**: Arthritis, dermatological, neurological, renal, or other systemic symptoms
    - **Specific**: Nephritis, kidney disease, or specific organ involvement (e.g., pulmonary, cardiac)

2. **Disease Activity
══════════════════════════════════════════════════════════════════════


══════════════════════════════════════════════════════════════════════
❓ QUESTION: A child presents with high fever, stiff neck, photophobia, and a petechial rash. What is the differential diagnosis and emergency treatment?
──────────────────────────────────────────────────────────────────────
🔴 BEFORE FINE-TUNING:
Given the symptoms of high fever, stiff neck, photophobia (fear of light), and petechial rash in a child, here's a step-by-step approach to determine the differential diagnosis and potential emergency treatment:

**Differential Diagnosis:**

1. **Infectious Diseases**: The presence of fever, stiff neck, and petechial rash suggests an infectious cause.
2. **Neurological Conditions**: The stiff neck and photophobia could indicate meningitis or encephalitis, which require immediate attention.
3. **Bloodborne Pathogens**: Petechial rash can be associated with viral infections such as herpes simplex virus (HSV) or varicella-zoster virus (VZV).
4. **Other Possible Causes**: Other possible causes include allergic reactions, autoimmune disorders, or other systemic illnesses.

**Emergency Treatment:**

Considering the severity of symptoms, I would recommend the following emergency treatment:

1. **Administer Antibiotics**: Administer intravenous antibiotics (e.g., ceftriaxone or vancomycin) to cover a broad spectrum of pathogens, including Streptococcus pneumoniae, Haemophilus influenzae, and Neisseria gonorrhoeae.
2. **Antiviral Therapy**: For HSV or VZV infection, consider antiviral medications like acyclovir or valacyclovir.
3. **Fluid Resuscitation**: Provide aggressive fluid resuscitation to manage dehydration and prevent shock.
4. **Oxygen Support**: Ensure adequate oxygenation by providing supplemental oxygen if necessary.
5. **Monitoring**: Continuously monitor the child for signs of worsening symptoms, such as increased fever, stiff neck, or changes in mental status.
6. **Phototherapy**: Consider phototherapy (UV-A light therapy) to treat HSV or VZV infection, especially if antiviral medication is not effective.
7. **Immunoglobulin**: Administer immunoglobulin (IVIG) to treat Kawasaki disease
──────────────────────────────────────────────────────────────────────
🟢 AFTER FINE-TUNING:
**Differential Diagnosis:**

1. **Meningitis**: The combination of high fever, stiff neck (indicative of meningeal irritation), and petechial rash (suggestive of vasculitic inflammation) points towards meningitis as a primary concern.
2. **Encephalitis**: Similar to meningitis, but without meningeal irritation, which might be less likely in infants or very young children due to their lack of protective skull bone.
3. **Infectious Meningoencephalitis**: A rare but serious condition caused by pathogens such as Neisseria meningitidis, Haemophilus influenzae type b, Streptococcus pneumoniae, or Cryptococcus neoformans.
4. **Viral infections**: Encephalitis can also be caused by viral infections like herpes simplex virus, varicella-zoster virus, or enteroviruses.

**Emergency Treatment:**

1. **Antibiotics**: Administer broad-spectrum antibiotics (e.g., ceftriaxone, cefotaxime) to cover for potential bacterial causes of meningitis, including Neisseria meningitidis, H. influenzae type b, S. pneumoniae, and C. neoformans.
2. **Fluid resuscitation**: Ensure adequate hydration through IV fluids (e.g., normal saline) to prevent dehydration and cerebral edema.
3. **Oxygen therapy**: Provide supplemental oxygen if the patient shows signs of hypoxia (e.g., decreased level of consciousness).
4. **Corticosteroids**: Administer corticosteroids (e.g., dexamethasone) to reduce inflammation and edema in the meninges.
5. **Anti-arrhythmics**: Use anti-arrhythmic medications (e.g., lidofenone) to control ventricular arrhythmias that may occur in some cases of encephalitis.
6. **Neurological monitoring**:
══════════════════════════════════════════════════════════════════════

In [ ]:
# DataFrame for easy review
import pandas as pd

rows = []
for q in BENCHMARK_QUESTIONS:
    rows.append({
        "Question"    : q[:80] + "...",
        "Before (len)": len(before_answers[q]),
        "After (len)" : len(after_answers[q]),
        "Before"      : before_answers[q][:300],
        "After"       : after_answers[q][:300],
    })

comparison_df = pd.DataFrame(rows)
pd.set_option('display.max_colwidth', 200)
comparison_df[["Question", "Before (len)", "After (len)"]]

,Question,Before (len),After (len)
0,What is the first-line treatment for Type 2 Diabetes Mellitus in a newly diagnos...,1789,1538
1,A 65-year-old male presents with sudden onset chest pain radiating to the left a...,1841,1651
2,Explain the mechanism of action of beta-lactam antibiotics and describe two mech...,1858,1805
3,What are the diagnostic criteria for Systemic Lupus Erythematosus (SLE) accordin...,1464,1552
4,"A child presents with high fever, stiff neck, photophobia, and a petechial rash....",1823,1610

## 10. Merge LoRA Weights & Save Full Model

This merges the LoRA adapter back into the base model weights for standalone deployment (no PEFT dependency needed at inference time).

In [ ]:

MERGE_AND_SAVE = True  

if MERGE_AND_SAVE:
    from peft import AutoPeftModelForCausalLM

    print("Loading adapter from disk for merge...")
    merged_model = AutoPeftModelForCausalLM.from_pretrained(
        adapter_path,
        low_cpu_mem_usage=True,
        torch_dtype=torch.float16,
        device_map="auto",
    )

    print("Merging LoRA weights into base model...")
    merged_model = merged_model.merge_and_unload()

    merged_path = os.path.join(OUTPUT_DIR, "merged_model")
    merged_model.save_pretrained(merged_path, safe_serialization=True)
    tokenizer.save_pretrained(merged_path)

    print(f" Merged model saved to: {merged_path}")
    !ls -lh {merged_path}
else:
    print("ℹ Merge skipped. Using adapter-only model.")

Loading adapter from disk for merge...
Merging LoRA weights into base model...
✅ Merged model saved to: ./llama-medical-qlora/merged_model
total 2.4G
-rw-r--r-- 1 root root  926 Mar 19 19:42 config.json
-rw-r--r-- 1 root root  184 Mar 19 19:42 generation_config.json
-rw-r--r-- 1 root root 2.4G Mar 19 19:43 model.safetensors
-rw-r--r-- 1 root root  325 Mar 19 19:43 special_tokens_map.json
-rw-r--r-- 1 root root  54K Mar 19 19:43 tokenizer_config.json
-rw-r--r-- 1 root root  17M Mar 19 19:43 tokenizer.json

## 11. Push Adapter to HuggingFace Hub

In [ ]:
PUSH_TO_HUB = False   # Set True to push

if PUSH_TO_HUB and HF_USERNAME:
    repo_id = f"{HF_USERNAME}/{ADAPTER_NAME}"
    print(f"Pushing adapter to: {repo_id}")

    trainer.model.push_to_hub(repo_id, private=True)
    tokenizer.push_to_hub(repo_id, private=True)

    print(f" Adapter pushed to: https://huggingface.co/{repo_id}")
else:
    print("ℹHub push skipped. Set PUSH_TO_HUB=True and HF_USERNAME to enable.")

## 12. Run with Ollama

Ollama is a lightweight local inference server. It requires the **merged** model exported to GGUF format.

> **Note:** Ollama runs best **locally** (not on Colab), since it needs a persistent server process. The cells below show how to export and use it.

In [ ]:
USE_OLLAMA = True 

if USE_OLLAMA:
    import subprocess, time, requests, os, pathlib

    print("Installing zstd dependency...")
    !apt-get install -qq -y zstd

    print("\nInstalling Ollama...")
    !curl -fsSL https://ollama.com/install.sh | sh

    if not pathlib.Path("/usr/local/bin/ollama").exists():
        raise FileNotFoundError(
            "Ollama binary not found after install.\n"
            "Try running: !curl -fsSL https://ollama.com/install.sh | sh"
        )
    print(" Ollama installed:", subprocess.run(["ollama", "--version"],
          capture_output=True, text=True).stdout.strip())

    print("\nStarting Ollama server...")
    server_env = os.environ.copy()
    server_env["OLLAMA_HOST"] = "0.0.0.0:11434"

    server_proc = subprocess.Popen(
        ["ollama", "serve"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=server_env,
    )

    for attempt in range(30):
        time.sleep(1)
        try:
            r = requests.get("http://localhost:11434", timeout=1)
            if r.status_code == 200:
                print(f" Ollama server ready (after {attempt+1}s).")
                break
        except Exception:
            pass
    else:
        # Print stderr to help debug
        err = server_proc.stderr.read(2000).decode(errors="replace")
        raise RuntimeError(f"Ollama server did not start in 30s.\nStderr: {err}")


    OLLAMA_MODEL = "llama3.2:1b"
    print(f"\nPulling {OLLAMA_MODEL} from Ollama Hub...")
    print("(This downloads ~2 GB — takes a few minutes on Colab)")
    !ollama pull {OLLAMA_MODEL}


    # Uncomment this block if you ran Section 10 (merge) and want to test
    # your fine-tuned model via Ollama instead of the base model.
    #
    # merged_path = os.path.abspath(os.path.join(OUTPUT_DIR, "merged_model"))
    # if os.path.isdir(merged_path):
    #     print(f"\nCreating Ollama model from merged weights: {merged_path}")
    #     modelfile = f'''FROM {merged_path}
    # SYSTEM "{SYSTEM_PROMPT}"
    # PARAMETER temperature 0.3
    # PARAMETER top_p 0.9
    # '''
    #     with open("/tmp/Modelfile", "w") as f:
    #         f.write(modelfile)
    #     !ollama create llama-medical -f /tmp/Modelfile
    #     OLLAMA_MODEL = "llama-medical"
    # else:
    #     print(f" Merged model not found at {merged_path}. Using pulled model.")

    print(f"\n Running inference with Ollama ({OLLAMA_MODEL})...")

    for i, question in enumerate(BENCHMARK_QUESTIONS, 1):
        print(f"\n[{i}/{len(BENCHMARK_QUESTIONS)}] ❓ {question[:80]}...")
        try:
            resp = requests.post(
                "http://localhost:11434/api/generate",
                json={
                    "model": OLLAMA_MODEL,
                    "prompt": question,
                    "system": SYSTEM_PROMPT,
                    "stream": False,
                    "options": {"temperature": 0.3, "top_p": 0.9},
                },
                timeout=120,
            )
            resp.raise_for_status()
            answer = resp.json().get("response", "(no response)")
            print(f" {answer[:400]}")
        except Exception as e:
            print(f" Error: {e}")

    print("\n Ollama inference complete.")

else:
    print("ℹ Ollama skipped. Set USE_OLLAMA=True to enable.")

Installing zstd dependency...
Selecting previously unselected package zstd.
(Reading database ... 121852 files and directories currently installed.)
Preparing to unpack .../zstd_1.4.8+dfsg-3build1_amd64.deb ...
Unpacking zstd (1.4.8+dfsg-3build1) ...
Setting up zstd (1.4.8+dfsg-3build1) ...
Processing triggers for man-db (2.10.2-1) ...

Installing Ollama...
>>> Cleaning up old version at /usr/local/lib/ollama
>>> Installing ollama to /usr/local
>>> Downloading ollama-linux-amd64.tar.zst
######################################################################## 100.0%
>>> Creating ollama user...
>>> Adding ollama user to video group...
>>> Adding current user to ollama group...
>>> Creating ollama systemd service...
WARNING: systemd is not running
WARNING: Unable to detect NVIDIA/AMD GPU. Install lspci or lshw to automatically detect and install GPU dependencies.
>>> The Ollama API is now available at 127.0.0.1:11434.
>>> Install complete. Run "ollama" from the command line.
✅ Ollama installed: Warning: could not connect to a running Ollama instance
Warning: client version is 0.18.2

Starting Ollama server...
✅ Ollama server ready (after 2s).

Pulling llama3.2:3b from Ollama Hub...
(This downloads ~2 GB — takes a few minutes on Colab)


🦙 Running inference with Ollama (llama3.2:3b)...

[1/5] ❓ What is the first-line treatment for Type 2 Diabetes Mellitus in a newly diagnos...
💬 The first-line treatment for Type 2 Diabetes Mellitus (T2DM) in a newly diagnosed patient involves a multifaceted approach that includes lifestyle modifications and pharmacological interventions. According to the American Diabetes Association (ADA) and the European Association for the Study of Diabetes (EASD), the following steps are recommended:

**Lifestyle Modifications:**

1. **Weight Loss:**

[2/5] ❓ A 65-year-old male presents with sudden onset chest pain radiating to the left a...
💬 **Diagnosis:**

Based on the patient's symptoms of sudden onset chest pain radiating to the left arm, diaphoresis, and nausea, the most likely diagnosis is Acute Coronary Syndrome (ACS), specifically Non-ST-Elevation Myocardial Infarction (NSTEMI) or ST-Elevation Myocardial Infarction (STEMI).

The symptoms presented are classic for ACS:

1. Chest pain: The patient's chest pain is a key symptom, a

[3/5] ❓ Explain the mechanism of action of beta-lactam antibiotics and describe two mech...
💬 **Mechanism of Action of Beta-Lactam Antibiotics:**

Beta-lactam antibiotics are a class of antimicrobials that inhibit bacterial cell wall synthesis, ultimately leading to bacterial death. The mechanism of action involves the inhibition of enzymes involved in peptidoglycan (also known as murein) synthesis.

The process can be broken down into several steps:

1. **Penicillin-binding proteins (PBPs

[4/5] ❓ What are the diagnostic criteria for Systemic Lupus Erythematosus (SLE) accordin...
💬 The 2019 EULAR/ACR classification of Systemic Lupus Erythematosus (SLE) introduced a revised set of diagnostic criteria, which are as follows:

**Major Criteria:**

1. **Discoid rash**: A characteristic butterfly-shaped rash on the face.
2. **Photodermatosis**: A skin rash that worsens with sunlight exposure.
3. **Oral ulcers**: Painful ulcers in the mouth or lips.
4. **Arthritis**: Arthritis, par

[5/5] ❓ A child presents with high fever, stiff neck, photophobia, and a petechial rash....
💬 **Clinical Presentation:** The child's symptoms of high fever, stiff neck, photophobia, and a petechial rash are highly suggestive of **Meningitis**, specifically **Viral Meningitis**.

**Differential Diagnosis:**

While meningitis is the primary consideration, other conditions that may present with similar symptoms include:

1. **Bacterial Meningitis**: Although less common in children, bacterial

✅ Ollama inference complete.